# Generated by Django 3.1.7 on 2021-04-07 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('descript', models.TextField(verbose_name='Описание')),
                ('author', models.TextField(default='Неизвестен', max_length=50, verbose_name='Автор')),
                ('post_date', models.DateField(auto_now_add=True, null=True)),
                ('file', models.FileField(blank=True, upload_to='')),
                ('duration', models.FloatField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='podcasts')),
                ('listened', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
            options={
                'verbose_name': 'Подкаст',
                'verbose_name_plural': 'Подкасты',
            },
        ),
    ]
