# Generated by Django 3.1.7 on 2021-04-09 08:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='likes',
        ),
        migrations.AddField(
            model_name='podcast',
            name='likes',
            field=models.ManyToManyField(related_name='podcast_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='listened',
        ),
        migrations.AddField(
            model_name='podcast',
            name='listened',
            field=models.ManyToManyField(related_name='podcast_listened', to=settings.AUTH_USER_MODEL),
        ),
    ]
