# Generated by Django 3.1.7 on 2021-04-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210417_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/audio/'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/img/'),
        ),
    ]
