# Generated by Django 3.1.7 on 2021-04-17 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210417_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='listened',
        ),
    ]
