# Generated by Django 3.1.7 on 2021-04-17 10:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_auto_20210417_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='podcast_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='podcast',
            name='listened',
            field=models.ManyToManyField(blank=True, default=None, related_name='podcast_listened', to=settings.AUTH_USER_MODEL),
        ),
    ]
